package com.alexurangareyes.myrealm;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

/**
 * Created by alexurangareyes on 6/26/16.
 */
public class Person extends RealmObject {
    @PrimaryKey
    private long id;
    private String name;

    // Standard getters & setters generated by your IDE…
    public void   setId(long id) {
        this.id = id;
    }
    public long getId() {
        return id;
    }


    public void   setName(String name) {
        this.name = name;
    }
    public String getName() {
        return name;
    }

}